# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartHouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kongtiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='kongtiao',
            field=models.ManyToManyField(to='smartHouse.kongtiao'),
        ),
    ]
